### ISSUE TITLE
Setup / environment.yml

### ISSUE THREAD

**Issue by Punicagranatum** [noahzn/Lite-Mono#23]
Hi,
I tried running test_simple.py with lite-mono-tiny, however I get an error. Since there are no setup instructions or an environment.yml file provided I assume that I am using a wrong version of pytorch. Can you please provide the setup information.

This is the error:
```
python test_simple.py --load_weights_folder weights/lite-mono-tiny_640x192 --image_path img/data/WIN_20230427_19_29_04_Pro.jpg
-> Loading model from  weights/lite-mono-tiny_640x192
   Loading pretrained encoder
Traceback (most recent call last):
  File "C:\git\Lite-Mono\test_simple.py", line 192, in <module>
    test_simple(args)
  File "C:\git\Lite-Mono\test_simple.py", line 86, in test_simple
    encoder.load_state_dict({k: v for k, v in encoder_dict.items() if k in model_dict})
  File "C:\Users\jon\AppData\Local\mambaforge\envs\litemono\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LiteMono:
        Missing key(s) in state_dict: "stages.2.6.ddwconv.conv.weight", "stages.2.6.bn1.weight", "stages.2.6.bn1.bias", "stages.2.6.bn1.running_mean", "stages.2.6.bn1.running_var", "stages.2.7.gamma", "stages.2.7.ddwconv.conv.weight", "stages.2.7.bn1.weight", "stages.2.7.bn1.bias", "stages.2.7.bn1.running_mean", "stages.2.7.bn1.running_var", "stages.2.7.norm.weight", "stages.2.7.norm.bias", "stages.2.7.pwconv1.weight", "stages.2.7.pwconv1.bias", "stages.2.7.pwconv2.weight", "stages.2.7.pwconv2.bias", "stages.2.8.gamma", "stages.2.8.ddwconv.conv.weight", "stages.2.8.bn1.weight", "stages.2.8.bn1.bias", "stages.2.8.bn1.running_mean", "stages.2.8.bn1.running_var", "stages.2.8.norm.weight", "stages.2.8.norm.bias", "stages.2.8.pwconv1.weight", "stages.2.8.pwconv1.bias", "stages.2.8.pwconv2.weight", "stages.2.8.pwconv2.bias", "stages.2.9.gamma_xca", "stages.2.9.gamma", "stages.2.9.norm_xca.weight", "stages.2.9.norm_xca.bias", "stages.2.9.xca.temperature", "stages.2.9.xca.qkv.weight", "stages.2.9.xca.qkv.bias", "stages.2.9.xca.proj.weight", "stages.2.9.xca.proj.bias", "stages.2.9.norm.weight", "stages.2.9.norm.bias", "stages.2.9.pwconv1.weight", "stages.2.9.pwconv1.bias", "stages.2.9.pwconv2.weight", "stages.2.9.pwconv2.bias".
        size mismatch for downsample_layers.0.0.conv.weight: copying a param with shape torch.Size([32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 3, 3, 3]).
        size mismatch for downsample_layers.0.0.bn_gelu.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.0.bn_gelu.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.0.bn_gelu.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.0.bn_gelu.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.1.conv.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 48, 3, 3]).
        size mismatch for downsample_layers.0.1.bn_gelu.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.1.bn_gelu.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.1.bn_gelu.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.1.bn_gelu.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.2.conv.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 48, 3, 3]).
        size mismatch for downsample_layers.0.2.bn_gelu.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.2.bn_gelu.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.2.bn_gelu.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.0.2.bn_gelu.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for downsample_layers.1.0.conv.weight: copying a param with shape torch.Size([64, 67, 3, 3]) from checkpoint, the shape in current model is torch.Size([80, 99, 3, 3]).
        size mismatch for downsample_layers.2.0.conv.weight: copying a param with shape torch.Size([128, 131, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 163, 3, 3]).
        size mismatch for stem2.0.conv.weight: copying a param with shape torch.Size([32, 35, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 51, 3, 3]).
        size mismatch for stages.0.0.gamma: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.0.ddwconv.conv.weight: copying a param with shape torch.Size([32, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 1, 3, 3]).
        size mismatch for stages.0.0.bn1.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.0.bn1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.0.bn1.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.0.bn1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.0.norm.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.0.norm.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.0.pwconv1.weight: copying a param with shape torch.Size([192, 32]) from checkpoint, the shape in current model is torch.Size([288, 48]).
        size mismatch for stages.0.0.pwconv1.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([288]).
        size mismatch for stages.0.0.pwconv2.weight: copying a param with shape torch.Size([32, 192]) from checkpoint, the shape in current model is torch.Size([48, 288]).
        size mismatch for stages.0.0.pwconv2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.gamma: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.ddwconv.conv.weight: copying a param with shape torch.Size([32, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 1, 3, 3]).
        size mismatch for stages.0.1.bn1.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.bn1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.bn1.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.bn1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.norm.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.norm.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.1.pwconv1.weight: copying a param with shape torch.Size([192, 32]) from checkpoint, the shape in current model is torch.Size([288, 48]).
        size mismatch for stages.0.1.pwconv1.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([288]).
        size mismatch for stages.0.1.pwconv2.weight: copying a param with shape torch.Size([32, 192]) from checkpoint, the shape in current model is torch.Size([48, 288]).
        size mismatch for stages.0.1.pwconv2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.gamma: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.ddwconv.conv.weight: copying a param with shape torch.Size([32, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 1, 3, 3]).
        size mismatch for stages.0.2.bn1.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.bn1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.bn1.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.bn1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.norm.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.norm.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.2.pwconv1.weight: copying a param with shape torch.Size([192, 32]) from checkpoint, the shape in current model is torch.Size([288, 48]).
        size mismatch for stages.0.2.pwconv1.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([288]).
        size mismatch for stages.0.2.pwconv2.weight: copying a param with shape torch.Size([32, 192]) from checkpoint, the shape in current model is torch.Size([48, 288]).
        size mismatch for stages.0.2.pwconv2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.gamma_xca: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.gamma: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.pos_embd.token_projection.weight: copying a param with shape torch.Size([32, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([48, 64, 1, 1]).     
        size mismatch for stages.0.3.pos_embd.token_projection.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.norm_xca.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.norm_xca.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.xca.qkv.weight: copying a param with shape torch.Size([96, 32]) from checkpoint, the shape in current model is torch.Size([144, 48]).
        size mismatch for stages.0.3.xca.qkv.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([144]).
        size mismatch for stages.0.3.xca.proj.weight: copying a param with shape torch.Size([32, 32]) from checkpoint, the shape in current model is torch.Size([48, 48]).
        size mismatch for stages.0.3.xca.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.norm.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.norm.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.0.3.pwconv1.weight: copying a param with shape torch.Size([192, 32]) from checkpoint, the shape in current model is torch.Size([288, 48]).
        size mismatch for stages.0.3.pwconv1.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([288]).
        size mismatch for stages.0.3.pwconv2.weight: copying a param with shape torch.Size([32, 192]) from checkpoint, the shape in current model is torch.Size([48, 288]).
        size mismatch for stages.0.3.pwconv2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for stages.1.0.gamma: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.0.ddwconv.conv.weight: copying a param with shape torch.Size([64, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([80, 1, 3, 3]).
        size mismatch for stages.1.0.bn1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.0.bn1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.0.bn1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.0.bn1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.0.norm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.0.norm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.0.pwconv1.weight: copying a param with shape torch.Size([384, 64]) from checkpoint, the shape in current model is torch.Size([480, 80]).
        size mismatch for stages.1.0.pwconv1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([480]).
        size mismatch for stages.1.0.pwconv2.weight: copying a param with shape torch.Size([64, 384]) from checkpoint, the shape in current model is torch.Size([80, 480]).
        size mismatch for stages.1.0.pwconv2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.gamma: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.ddwconv.conv.weight: copying a param with shape torch.Size([64, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([80, 1, 3, 3]).
        size mismatch for stages.1.1.bn1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.bn1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.bn1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.bn1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.norm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.norm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.1.pwconv1.weight: copying a param with shape torch.Size([384, 64]) from checkpoint, the shape in current model is torch.Size([480, 80]).
        size mismatch for stages.1.1.pwconv1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([480]).
        size mismatch for stages.1.1.pwconv2.weight: copying a param with shape torch.Size([64, 384]) from checkpoint, the shape in current model is torch.Size([80, 480]).
        size mismatch for stages.1.1.pwconv2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.gamma: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.ddwconv.conv.weight: copying a param with shape torch.Size([64, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([80, 1, 3, 3]).
        size mismatch for stages.1.2.bn1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.bn1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.bn1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.bn1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.norm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.norm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.2.pwconv1.weight: copying a param with shape torch.Size([384, 64]) from checkpoint, the shape in current model is torch.Size([480, 80]).
        size mismatch for stages.1.2.pwconv1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([480]).
        size mismatch for stages.1.2.pwconv2.weight: copying a param with shape torch.Size([64, 384]) from checkpoint, the shape in current model is torch.Size([80, 480]).
        size mismatch for stages.1.2.pwconv2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.gamma_xca: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.gamma: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.norm_xca.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.norm_xca.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.xca.qkv.weight: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([240, 80]).
        size mismatch for stages.1.3.xca.qkv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([240]).
        size mismatch for stages.1.3.xca.proj.weight: copying a param with shape torch.Size([64, 64]) from checkpoint, the shape in current model is torch.Size([80, 80]).
        size mismatch for stages.1.3.xca.proj.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.norm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.norm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for stages.1.3.pwconv1.weight: copying a param with shape torch.Size([384, 64]) from checkpoint, the shape in current model is torch.Size([480, 80]).
        size mismatch for stages.1.3.pwconv1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([480]).
        size mismatch for stages.1.3.pwconv2.weight: copying a param with shape torch.Size([64, 384]) from checkpoint, the shape in current model is torch.Size([80, 480]).
        size mismatch for stages.1.3.pwconv2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
```

**Comment by noahzn** [comment]
Hi @Punicagranatum , the errors show that you are trying to load the weights of `lite-mono-tiny` to `lite-mono`. You can use `--model` to decide which model to load and please make sure you use the correct weights.

**Comment by Punicagranatum** [comment]
Hey @noahzn,
Thank you for your quick help. I did not see there was a `--model` argument. Now it works.
