### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by nameless-2019302413** [noahzn/Lite-Mono#46]
when I run  python train.py --data_path  /mypath --model_name mytrain --num_epochs 30 --batch_size 12 --mypretrain ./weight/lite-mono-8m_1024x320 --lr 0.0001 5e-6 31 0.0001 1e-5 31,
that display "Traceback (most recent call last):
  File "E:\qitaxiangmu\Lite-Mono\train.py", line 11, in <module>
    trainer = Trainer(opts)
  File "E:\qitaxiangmu\Lite-Mono\trainer.py", line 71, in __init__
    self.models_pose["pose_encoder"] = networks.ResnetEncoder(
  File "E:\qitaxiangmu\Lite-Mono\networks\resnet_encoder.py", line 76, in __init__
    self.encoder = resnet_multiimage_input(num_layers, pretrained, num_input_images)
  File "E:\qitaxiangmu\Lite-Mono\networks\resnet_encoder.py", line 48, in resnet_multiimage_input
    loaded = model_zoo.load_url(models.resnet.model_urls['resnet{}'.format(num_layers)])
  File "E:\qitaxiangmu\Track-Anything\venv\lib\site-packages\torch\hub.py", line 735, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "E:\qitaxiangmu\Track-Anything\venv\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\qitaxiangmu\Track-Anything\venv\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))"

**Comment by noahzn** [comment]
Hi, if you set `--mypretrain` you should input an ImageNet pre-trained file. So you should use something like this `--mypretrain ./weight/lite-mono-8m-pretrain.pth`

**Comment by nameless-2019302413** [comment]
Thank you. This problem should be caused by my network problem
